"""add validation_flags column

Revision ID: a3f9f1497c2e
Revises: 97aa66d23b9a
Create Date: 2026-08-02 21:47:32.628327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3f9f1497c2e'
down_revision: Union[str, Sequence[str], None] = '97aa66d23b9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('validation_flags', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'validation_flags')
    # ### end Alembic commands ###
