"""add few more fields to document model

Revision ID: a5d5618de91f
Revises: a3f9f1497c2e
Create Date: 2026-08-29 10:33:41.356795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5d5618de91f'
down_revision: Union[str, Sequence[str], None] = 'a3f9f1497c2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('supplier', sa.String(length=255), nullable=True))
    op.add_column('documents', sa.Column('document_date', sa.Date(), nullable=True))
    op.add_column('documents', sa.Column('total_amount', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'total_amount')
    op.drop_column('documents', 'document_date')
    op.drop_column('documents', 'supplier')
    # ### end Alembic commands ###
