"""split transaction into header and lines

Revision ID: 97aa66d23b9a
Revises: 0fc3d1b757e2
Create Date: 2026-08-02 13:18:51.242386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97aa66d23b9a'
down_revision: Union[str, Sequence[str], None] = '0fc3d1b757e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('cont', sa.String(length=20), nullable=False),
    sa.Column('tip', sa.String(length=10), nullable=False),
    sa.Column('suma', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('transactions', sa.Column('necesita_verificare', sa.Boolean(), nullable=False))
    op.add_column('transactions', sa.Column('observatii', sa.String(length=500), nullable=True))
    op.drop_column('transactions', 'debit_account')
    op.drop_column('transactions', 'amount')
    op.drop_column('transactions', 'credit_account')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('credit_account', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('transactions', sa.Column('amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
    op.add_column('transactions', sa.Column('debit_account', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('transactions', 'observatii')
    op.drop_column('transactions', 'necesita_verificare')
    op.drop_table('transaction_lines')
    # ### end Alembic commands ###
